### ISSUE TITLE
Porting to 1.20+?

### ISSUE THREAD

**Issue by mercury19** [Elite-Modding-Team/HarkenScythe#1]
Are there any plans to do a modern port? If not, would it be alright if I attempted to port it myself? 

I've never done it before but I was feeling nostalgic for this mod the other day and I like to challenge myself, so I thought I would ask here if it was ok/if you already planned to.

**Comment by ACGaming** [comment]
This is specifically designed for Hexxit II, so it's staying at 1.12.2. As we are essentially a legacy modding team, there are no plans for updating any of our mods to _modern_ versions of the game.

Since our Harken Scythe remake is licensed as GPLv3, anyone is free to port when keeping the same license. Keep in mind that the mod is heavily WIP and not released yet, so I'd advise against porting efforts just yet.
